language: node_js
node_js:
  - 6
cache:
  directories:
    - node_modules
script:
  - yarn build
  - yarn test
after_success:
  -ssh root@139.199.188.225 -p 22 'cd /msg-board && sudo git pull && yarn start'
